spring.application.name=WebAppProd
server.port=8081

# Logging
logging.level.org=info
logging.level.com.pioneers.refactor=trace

db.url=jdbc://192.168.0.10:1234:db
db.username=testUser
db.password=!hFed#12Lkdj


student.egyptian.user-name=Esraa Amr
student.egyptian.age=23
student.egyptian.email=esraa.amr@techpioneershub.com
student.egyptian.address.continent=Africa
student.egyptian.address.country=Egypt
student.egyptian.address.governorate=Cairo
student.egyptian.address.city=Nasr City
student.egyptian.address.street=Omar bn Elkhatab
student.egyptian.address.building-number=100
student.egyptian.address.floor=1
student.egyptian.address.apartment-number=4